use_frameworks!

platform :ios, '13.0'

target 'TronWalletWeb3Swift_Example' do
  pod 'TronWalletWeb3Swift', :path => '../'

  target 'TronWalletWeb3Swift_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Xcode 26: Explicit Modules break CocoaPods deps.
      config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
      # Xcode removed libarclite; old pod deployment targets still require it.
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
